Repository puppetlabs/puppetlabs-java_ks, pull requests merged in 2019-01, with the labels that each got.

#258 pdksync - pdksync_heads/master-0-g9c815ea
  .travis.yml
  metadata.json
Labels: maintenance

#259 pdksync - pdksync_heads/master-0-g6814a87
  .travis.yml
  Gemfile
  appveyor.yml
  metadata.json
Labels: maintenance

#260 (MODULES-8549) - Bump of Java version used for test
  spec/acceptance/destkeypass_spec.rb
  spec/acceptance/keystore_spec.rb
  spec/acceptance/pkcs12_spec.rb
  spec/spec_helper_acceptance.rb
Labels: bugfix

#263 pdksync - pdksync_1.9.0-0-g7281db5
  .puppet-lint.rc
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#261 (FM-7724) - Remove Windows 8 testing/support
  metadata.json
Labels: backwards-incompatible

#262 (FM-7720/FM-7722/FM-7723) Consolidate Windows Metadata
  metadata.json
Labels: bugfix
