Repository puppetlabs/puppetlabs-java_ks, pull requests merged in 2020-11, with the labels that each got.

#335 (IAC-994) Removal of inappropriate terminology
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  CONTRIBUTING.md
  README.md
  metadata.json
Labels: feature

#336 Change latest/current comparison to account for chains
  lib/puppet/type/java_ks.rb
Labels: bugfix

#337 (Maint) Release version 3.3.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#338 pdksync - Update pdk-templates for gitpod and codespaces support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitpod.Dockerfile
  .gitpod.yml
  .pdkignore
  .rubocop.yml
  .sync.yml
  Gemfile
  data/common.yaml
  hiera.yaml
  metadata.json
Labels: maintenance

#341 pdksync - (maint) Add release_checks_7 config to provision.yaml
  provision.yaml
Labels: maintenance
