Repository puppetlabs/puppetlabs-java_ks, pull requests merged in 2021-06, with the labels that each got.

#371 pdksync - (maint) PDKSync - PDK Update
  .github/workflows/auto_release.yml
  .github/workflows/release.yml
  .github/workflows/spec.yml
  .pdkignore
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#372 Fix fingerprint comparison
  lib/puppet/type/java_ks.rb
  spec/unit/puppet/type/java_ks_spec.rb
Labels: bugfix

#373 Accept Datatype Sensitive for Secrets
  lib/puppet/type/java_ks.rb
Labels: feature
