Repository puppetlabs/puppetlabs-java_ks, pull requests merged in 2022-10, with the labels that each got.

#416 pdksync - (PDKSync) Removal of puppet_module_gems
  .devcontainer/README.md
  Gemfile
  metadata.json
Labels: maintenance, hacktoberfest

#417 pdksync - (CONT-189) Remove support for RedHat6 / OracleLinux6 / Scientific6
  metadata.json
Labels: bugfix, hacktoberfest

#412 reversed insync set comparison
  lib/puppet/type/java_ks.rb
  spec/unit/puppet/type/java_ks_spec.rb
Labels: community
