Repository puppetlabs/puppetlabs-java_ks, pull requests merged in 2022-03, with the labels that each got.

#389 (GH-388) Temporary Windows Fix
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#390 pdksync - (GH-iac-334) Remove Support for Ubuntu 14.04/16.04
  metadata.json
Labels: bugfix

#391 pdksync - Add labeller and stale GHA workflows
  .github/workflows/labeller.yml
  .github/workflows/stale.yml
Labels: maintenance

#385 Add support for certificate_content and private_key_content parameters
  README.md
  lib/puppet/provider/java_ks/keytool.rb
  lib/puppet/type/java_ks.rb
  spec/acceptance/content_spec.rb
  spec/unit/puppet/provider/java_ks/keytool_spec.rb
  spec/unit/puppet/type/java_ks_spec.rb
Labels: feature, community
